#pragma once

namespace Localization {
    inline std::string SectionUtilities;
    inline std::string MenuItemLoadTimeProfiler;
    inline std::string Summary;
    inline std::string System;
    inline std::string SkseInitTimeHeuristic;
    inline std::string TotalDllTime;
    inline std::string TotalEspTime;
    inline std::string TotalTime;
    inline std::string CurrentlyLoadingDll;
    inline std::string CurrentlyLoadingEsp;
    inline std::string Selection;
    inline std::string ButtonAll;
    inline std::string ButtonNone;
    inline std::string HeaderDisplay;
    inline std::string ButtonSaveSettings;
    inline std::string CheckShowInSeconds;
    inline std::string HelpMarkerLabel;
    inline std::string HelpMarkerSeconds;
    inline std::string Thresholds;
    inline std::string HelpMarkerThresholds;
    inline std::string WarnMs;
    inline std::string CritMs;
    inline std::string HeaderMessageTypes;
    inline std::string SearchLabel;
    inline std::string SearchHint;
    inline std::string ExportFormatCsv;
    inline std::string ExportFormatTxt;
    inline std::string ExportFormatJson;
    inline std::string ExportButton;
    inline std::string ExportStatusSuccess;
    inline std::string ExportStatusFailed;
    inline std::string ExportSkyrimRuntimeVariant;
    inline std::string ExportSkyrimRuntimeVersion;
    inline std::string ExportOsNameVersion;
    inline std::string ExportCpuVendor;
    inline std::string ExportCpuModel;
    inline std::string ExportGpuList;
    inline std::string TypeDll;
    inline std::string TypeEsp;
    inline std::string NoMessageTypesSelected;
    inline std::string TotalSecondsLabel;
    inline std::string TotalMillisecondsLabel;
    inline std::string ColumnModule;
    inline std::string ColumnType;
    inline std::string TotalsRowLabel;
    inline std::string PlaceholderEmpty;
    inline std::string Author;
    inline std::string Version;
    inline std::string License;
    inline std::string TooltipNoVersionInfo;
    inline std::string FormatSeconds;
    inline std::string FormatMilliseconds;
    inline std::string MsgPostLoad;
    inline std::string MsgPostPostLoad;
    inline std::string MsgPreLoadGame;
    inline std::string MsgPostLoadGame;
    inline std::string MsgSaveGame;
    inline std::string MsgDeleteGame;
    inline std::string MsgInputLoaded;
    inline std::string MsgNewGame;
    inline std::string MsgDataLoaded;
    inline std::string MsgUnknown;
    inline std::string TipPostLoad;
    inline std::string TipPostPostLoad;
    inline std::string TipPreLoadGame;
    inline std::string TipPostLoadGame;
    inline std::string TipSaveGame;
    inline std::string TipDeleteGame;
    inline std::string TipInputLoaded;
    inline std::string TipNewGame;
    inline std::string TipDataLoaded;
    inline std::string Empty;

    void Load();
    std::string MakeLabel(const std::string& visible, const char* stableId);
    const std::string& MessageTypeLabel(std::size_t index);
    const std::string& MessageTypeTooltip(std::size_t index);
}