set(headers ${headers}
	include/Utils.h
	include/PCH.h
	include/Settings.h
	include/Hooks.h
	include/AssetReadProfiling.h
	include/ChangeFormProfiling.h
	include/ESPProfiling.h
	include/LoadProfiling.h
	include/DevBenchBridge.h
	include/MCP.h
	include/Events.h
	include/Export.h
	include/MessagingProfilerUI.h
	include/Localization.h
	include/Logger.h
	include/MessagingProfiler.h
	include/VRESLIntegration.h
)
